<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXxcxX5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXxcxX5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXxcxX5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXXxcxX5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXXxcxX5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XXxcxX5',
    'container.build_id' => '708d0c54',
    'container.build_time' => 1623263994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXxcxX5');
